GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/metadata
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

###
GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient/70264
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

###
GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient?_elements=id
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###
PUT http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient/70285
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

{
        "resourceType": "Patient",
        "id": "70285",
        "name": [{"given": ["Susan"], "family": "Doe"}],
        "active": true,
}
###

GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient/70285/_history
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

###
###
POST http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Bundle
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

{
  "resourceType": "Bundle",
  "type": "collection",
  "entry": [
    {
      "resource": {
        "resourceType": "Patient",
        "id": "123",
        "name": [{"given": ["John"], "family": "Doe"}],
        "gender": "male"
      }
    }
  ]
}
###