GET http://fhir.cloudintersystems.com/csp/healthshare/demo/fhir/r4/metadata
content-type: application/fhir+json
Accept: */*
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###
GET http://fhir.cloudintersystems.com/csp/healthshare/demo/fhir/r4/Patient
Authorization: Basic _System:ISCDEMO
content-type: application/fhir+ json
Accept: */*
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###
GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/metadata
Authorization: Basic _System:ISCDEMO
content-type: application/fhir+ json
Accept: */*
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###
GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+ json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###